# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jiayi/SVF-SourceCodeInfo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jiayi/SVF-SourceCodeInfo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"SvfLLVM\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jiayi/SVF-SourceCodeInfo/CMakeFiles /Users/jiayi/SVF-SourceCodeInfo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jiayi/SVF-SourceCodeInfo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SvfCore

# Build rule for target.
SvfCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SvfCore
.PHONY : SvfCore

# fast build rule for target.
SvfCore/fast:
	$(MAKE) $(MAKESILENT) -f svf/CMakeFiles/SvfCore.dir/build.make svf/CMakeFiles/SvfCore.dir/build
.PHONY : SvfCore/fast

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/CMakeFiles/intrinsics_gen.dir/build.make svf-llvm/CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/CMakeFiles/omp_gen.dir/build.make svf-llvm/CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/CMakeFiles/acc_gen.dir/build.make svf-llvm/CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/CMakeFiles/RISCVTargetParserTableGen.dir/build.make svf-llvm/CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named SvfLLVM

# Build rule for target.
SvfLLVM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SvfLLVM
.PHONY : SvfLLVM

# fast build rule for target.
SvfLLVM/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/CMakeFiles/SvfLLVM.dir/build.make svf-llvm/CMakeFiles/SvfLLVM.dir/build
.PHONY : SvfLLVM/fast

#=============================================================================
# Target rules for targets named install-SvfLLVM

# Build rule for target.
install-SvfLLVM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install-SvfLLVM
.PHONY : install-SvfLLVM

# fast build rule for target.
install-SvfLLVM/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/CMakeFiles/install-SvfLLVM.dir/build.make svf-llvm/CMakeFiles/install-SvfLLVM.dir/build
.PHONY : install-SvfLLVM/fast

#=============================================================================
# Target rules for targets named install-SvfLLVM-stripped

# Build rule for target.
install-SvfLLVM-stripped: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install-SvfLLVM-stripped
.PHONY : install-SvfLLVM-stripped

# fast build rule for target.
install-SvfLLVM-stripped/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/CMakeFiles/install-SvfLLVM-stripped.dir/build.make svf-llvm/CMakeFiles/install-SvfLLVM-stripped.dir/build
.PHONY : install-SvfLLVM-stripped/fast

#=============================================================================
# Target rules for targets named gen_extapi_ir

# Build rule for target.
gen_extapi_ir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_extapi_ir
.PHONY : gen_extapi_ir

# fast build rule for target.
gen_extapi_ir/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/CMakeFiles/gen_extapi_ir.dir/build.make svf-llvm/CMakeFiles/gen_extapi_ir.dir/build
.PHONY : gen_extapi_ir/fast

#=============================================================================
# Target rules for targets named saber

# Build rule for target.
saber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 saber
.PHONY : saber

# fast build rule for target.
saber/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/tools/SABER/CMakeFiles/saber.dir/build.make svf-llvm/tools/SABER/CMakeFiles/saber.dir/build
.PHONY : saber/fast

#=============================================================================
# Target rules for targets named wpa

# Build rule for target.
wpa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wpa
.PHONY : wpa

# fast build rule for target.
wpa/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/tools/WPA/CMakeFiles/wpa.dir/build.make svf-llvm/tools/WPA/CMakeFiles/wpa.dir/build
.PHONY : wpa/fast

#=============================================================================
# Target rules for targets named svf-ex

# Build rule for target.
svf-ex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 svf-ex
.PHONY : svf-ex

# fast build rule for target.
svf-ex/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/tools/Example/CMakeFiles/svf-ex.dir/build.make svf-llvm/tools/Example/CMakeFiles/svf-ex.dir/build
.PHONY : svf-ex/fast

#=============================================================================
# Target rules for targets named dvf

# Build rule for target.
dvf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dvf
.PHONY : dvf

# fast build rule for target.
dvf/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/tools/DDA/CMakeFiles/dvf.dir/build.make svf-llvm/tools/DDA/CMakeFiles/dvf.dir/build
.PHONY : dvf/fast

#=============================================================================
# Target rules for targets named mta

# Build rule for target.
mta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mta
.PHONY : mta

# fast build rule for target.
mta/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/tools/MTA/CMakeFiles/mta.dir/build.make svf-llvm/tools/MTA/CMakeFiles/mta.dir/build
.PHONY : mta/fast

#=============================================================================
# Target rules for targets named cfl

# Build rule for target.
cfl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cfl
.PHONY : cfl

# fast build rule for target.
cfl/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/tools/CFL/CMakeFiles/cfl.dir/build.make svf-llvm/tools/CFL/CMakeFiles/cfl.dir/build
.PHONY : cfl/fast

#=============================================================================
# Target rules for targets named llvm2svf

# Build rule for target.
llvm2svf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llvm2svf
.PHONY : llvm2svf

# fast build rule for target.
llvm2svf/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/tools/LLVM2SVF/CMakeFiles/llvm2svf.dir/build.make svf-llvm/tools/LLVM2SVF/CMakeFiles/llvm2svf.dir/build
.PHONY : llvm2svf/fast

#=============================================================================
# Target rules for targets named ae

# Build rule for target.
ae: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ae
.PHONY : ae

# fast build rule for target.
ae/fast:
	$(MAKE) $(MAKESILENT) -f svf-llvm/tools/AE/CMakeFiles/ae.dir/build.make svf-llvm/tools/AE/CMakeFiles/ae.dir/build
.PHONY : ae/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... gen_extapi_ir"
	@echo "... install-SvfLLVM"
	@echo "... install-SvfLLVM-stripped"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... SvfCore"
	@echo "... SvfLLVM"
	@echo "... ae"
	@echo "... cfl"
	@echo "... dvf"
	@echo "... llvm2svf"
	@echo "... mta"
	@echo "... saber"
	@echo "... svf-ex"
	@echo "... wpa"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

